---
- name: Configure Web Servers
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx Service
      service:
        name: nginx
        state: started

    - name: Deploy Web Application
      copy:
        src: /path/to/web_app/index.html
        dest: /var/www/html/index.html

- name: Configure Database Servers
  hosts: db
  become: yes
  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL Service
      service:
        name: mysql
        state: started

    - name: Create Database
      mysql_db:
        name: my_app_db
        state: present

    - name: Create Database User
      mysql_user:
        name: my_app_user
        password: securepassword
        priv: "my_app_db.*:ALL"
        state: present
