---
# Playbook to configure web and database servers for a multi-tier deployment

# Web Server Configuration
- name: Configure Web Servers                # Name of the play for web server setup
  hosts: web                                 # Target the 'web' group from the inventory file
  become: yes                                # Execute tasks with sudo privileges
  tasks:                                     # Define tasks to be executed
    - name: Install Nginx                    # Task to install the Nginx web server
      apt:                                   # Use the apt module to manage packages
        name: nginx                          # Specify the package name (Nginx)
        state: present                       # Ensure Nginx is installed

    - name: Start Nginx Service              # Task to start the Nginx service
      service:                               # Use the service module to manage services
        name: nginx                          # Service name (Nginx)
        state: started                       # Ensure the service is running

# Database Server Configuration
- name: Configure Database Servers           # Name of the play for database server setup
  hosts: db                                  # Target the 'db' group from the inventory file
  become: yes                                # Execute tasks with sudo privileges
  tasks:                                     # Define tasks to be executed
    - name: Install MySQL Server             # Task to install the MySQL server
      apt:                                   # Use the apt module to manage packages
        name: mysql-server                   # Specify the package name (MySQL server)
        state: present                       # Ensure MySQL server is installed

    - name: Start MySQL Service              # Task to start the MySQL service
      service:                               # Use the service module to manage services
        name: mysql                          # Service name (MySQL)
        state: started                       # Ensure the service is running

    - name: Create Database                  # Task to create a database
      mysql_db:                              # Use the mysql_db module for database management
        name: my_app_db                      # Name of the database to be created
        state: present                       # Ensure the database exists

    - name: Create Database User             # Task to create a database user
      mysql_user:                            # Use the mysql_user module for user management
        name: my_app_user                    # Name of the database user
        password: securepassword             # Password for the database user
        priv: "my_app_db.*:ALL"              # Grant all privileges on 'my_app_db' to the user
        state: present                       # Ensure the user exists
