---
- name: Multi-Tier Deployment
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx on Web Servers
      apt:
        name: nginx
        state: present

    - name: Start Nginx Service
      service:
        name: nginx
        state: started

- name: Install MySQL on DB Servers
  hosts: db
  become: yes
  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL Service
      service:
        name: mysql
        state: started
