---
# Playbook to configure web and database servers for a multi-tier deployment

# Web Server Configuration
- name: Configure Web Servers                # Name of the play for web server setup
  hosts: web                                 # Target the 'web' group from the inventory file
  become: yes                                # Execute tasks with sudo privileges
  tasks:                                     # Define tasks to be executed
    - name: Install Nginx                    # Task to install the Nginx web server
      apt:                                   # Use the apt module to manage packages
        name: nginx                          # Specify the package name (Nginx)
        state: present                       # Ensure Nginx is installed

    - name: Start Nginx Service              # Task to start the Nginx service
      service:                               # Use the service module to manage services
        name: nginx                          # Service name (Nginx)
        state: started                       # Ensure the service is running

# Redis Server Configuration
- name: Configure Redis Servers          # Define a play to set up Redis servers
  hosts: redis                           # Target the 'redis' group from the inventory file
  become: yes                            # Run tasks with elevated privileges (sudo)
  tasks:                                 # List of tasks to execute
    - name: Add Redis APT repository     # Add the official Redis repository to the APT sources
      apt_repository:                    # Use the apt_repository module for managing APT sources
        repo: "ppa:redislabs/redis"      # Specify the PPA (Personal Package Archive) for Redis
        state: present                   # Ensure the repository is added

    - name: Update APT cache             # Refresh the local APT cache to reflect the added repository
      apt:                               # Use the apt module for APT operations
        update_cache: yes                # Update the package index
        cache_valid_time: 3600           # Cache validity duration (in seconds)

    - name: Install Redis                # Install the Redis server package
      apt:                               # Use the apt module to install Redis
        name: redis-server               # Specify the Redis server package
        state: present                   # Ensure Redis is installed

    - name: Configure Redis to allow remote connections  # Modify Redis configuration for remote access
      lineinfile:                        # Use the lineinfile module to modify configuration files
        path: /etc/redis/redis.conf      # Specify the Redis configuration file
        regexp: '^bind '                 # Target the 'bind' directive for modification
        line: 'bind 0.0.0.0'             # Allow Redis to listen on all network interfaces
        state: present                   # Ensure the line exists in the file

    - name: Restart Redis service        # Restart Redis to apply configuration changes
      service:                           # Use the service module for service management
        name: redis-server               # Specify the Redis service name
        state: restarted                 # Restart the service
