---
- name: Install and Configure Nginx # Descriptive name for the playbook's purpose.
  hosts: web                     # Target the 'web' group in the inventory file.
  become: yes                    # Use sudo privileges for all tasks in this playbook.
  roles:                         # Defines the roles to be applied to the 'web' hosts.
    - nginx                      # Refers to the 'nginx' role, which contains predefined tasks, variables, and handlers for configuring Nginx.
