---
- name: Install and Configure Nginx # Descriptive name for the playbook's purpose.
  hosts: web                     # Target the 'web' group in the inventory file.
  become: yes                    # Use sudo privileges for all tasks in this playbook.
  roles:                      
    - nginx
    
